{% set name = "dask-image" %}
{% set version = "2026.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ed6b462277e691b2c12b0890ba801a0f9a00cc1894b0aa71b195a7a1419b2b00

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python
    - dask-core >=2024.4.1
    - numpy >=1.18
    - scipy >=1.7.0
    - pims >=0.4.1
    - tifffile >=2020.10.1
  run_constrained:
    # dataframe
    - pandas >=2.0.0
    # gpu
    - cupy >=9.0.0

test:
  source_files:
    - tests
  imports:
    - dask_image
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests 
  requires:
    - pytest >=7.2.2
    - pyarrow
    - pip

about:
  home: https://github.com/dask/dask-image
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed image processing
  description: Image processing with Dask Arrays
  doc_url: https://image.dask.org
  dev_url: https://github.com/dask/dask-image

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - jakirkham
    - m-albert
