{% set name = "dask-image" %}
{% set version = "2025.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 45cf1a9c3a8a1c143c75d43f1494e4fe0827564d3ec6efb93618fb04603ba0b3
  patches:
    - patches/fix-tests-unknown-old-dask-version.patch

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python
    - dask-core >=2024.4.1
    - numpy >=1.18
    - scipy >=1.7.0
    - pandas >=2.0.0
    - pims >=0.4.1
    - tifffile >=2018.10.18
  run_constrained:
    - cupy >=9.0.0

test:
  source_files:
    - tests
    - dask_image/_version.py
  imports:
    - dask_image
  requires:
    - pytest >=7.2.2
    - pyarrow
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests -v

about:
  home: https://github.com/dask/dask-image
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Distributed image processing
  description: Image processing with Dask Arrays
  doc_url: https://image.dask.org
  dev_url: https://github.com/dask/dask-image

extra:
  recipe-maintainers:
    - GenevieveBuckley
    - jakirkham
    - m-albert
