travis:
  secure:
    BINSTAR_TOKEN: FlA2oKg41AOVMPKpK5ri10GK0AVvqrt9teLaiQXyDINZeVZbvDmKOSTSQZ746soiAUyyAqMyfxGpanZv/fygVg/bbsEy84RGNr4aXhzeJyu7WOiUyGwqgf9T93AzNWCodAfRT3u1dSqB0WVDpAio1w3zWD6acc4/VCSsEX97kxnio8BSfjg+s/mp8K11HYjDGhutPIt6yNZWlBpVqOt4MyMr/iM4JOpG9Gn5Br0gRzoXtqv691uI4+SFANyAFSyfQEHwU91CPkHCNevnQCKd6HYnl5Q/MJDO+DToNYrB+r743u6+z5P8ejOHACg2s9hY3xOkpaR6rYjHLy1izoXqI6Fw2u6517/4Xh4yuICjxH5HFRnw8YcFHOp91MeCk03s6fg64PfwGFI4cpr7RcdTfed9R9oBRkmCafiDjzsaPbuwRg49BFV5k9xUJSubcWZz6tMM4OVKQWiFlCdrHrHaDMdYnGf+X9KL0i16qR8myv7GHMmx8SaxRwBP6hUVt1c2PGdaqSG0a6HWHUYNodDG2kYWNfM0nwsON2UncFSel8yGYln11MvZUs4CSrllL5MJokDuKj8Jgvl4lMDwcSXmil5G0yIvEZRwRyci8dAKcZSXppXZbu0E52AZ4QRSYXN9yFNvdiY9gFKJurruZ+z8lqtMd4B5+fqUUXEeh6Eo7ik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
